[theme]
base="light"
primaryColor="#002B49"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#FFFFFF"
textColor="#333333"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
